# Generated by Django 6.0.7 on 2026-07-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_product_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='features',
            new_name='featured',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
